# syntax=docker/dockerfile:1
FROM python:3.10.2-slim-bullseye
WORKDIR /web_server
RUN apt update && apt upgrade -y && apt install -y mariadb-client libmariadb-dev gcc && rm -rf /var/lib/apt/lists/* 
COPY . .
RUN pip install --progress-bar off --upgrade pip && pip install --progress-bar off -r requirements.txt
EXPOSE 5000
CMD [ "python", "app.py" ]
